### PR TITLE
Mobile webpage

### PR DESCRIPTION
**Pull request by andreasb242**
This pull is based on the last one. If you merge this first, the diff should be displayed correctly and only contain the new changes.

### CODE REVIEW

**Comment by woheller69** [comment]
thanks, will try in the next days

**Comment by woheller69** [comment]
I just made a first test. Cool stuff :-)

Some minor things so far:
- the http connection info is: http:///192.168.....  but should be http://.... so one "/" less, right?
- when switching from JPG mode to a video mode, the image most recent image should be removed from the website
- "Refresh to get current image / No image to display" should only be displayed while in JPG mode
- When you click "Refresh" in video mode also the last image is loaded which should not be the case
- if the port is changed, http:// info is not updated, only when you click on it
- For a release I would remove the Logger stuff. Or do you want to keep it? Then the log file should better be in the TimeLapseCam folder where also the images and videos are stored to have everything in one place
- Log.i(TAG, "Photo service destroyed"); in ForegroundService should better be "Recording service destroyed"
- In MainActivity there is a long uncommented block 	"// because of the crash it's not a"  which can probably be removed

So far I have not seen anything where I see a risk that something could have been broken :-)

**Comment by woheller69** [comment]
now it does not work anymore. It tells me it has no IP, but it is connectrd to a wifi and my webbrowser works.

Even restart of phone does not help

**Comment by woheller69** [comment]
Even reset of app data did not help. I had to reinstall. Now it works again. Ideas?

I also tried with a hotspot provided from the remote phone. Works well.

**Comment by andreasb242** [comment]
Thank you for the test report, yes, it's not fully finished yet.

>For a release I would remove the Logger stuff. Or do you want to keep it? Then the log file should better be in the TimeLapseCam folder where also the images and videos are stored to have everything in one place

I think you were on the wrong branch, the Logger was linked on the ticket, but not on this Pull, I added it later, and I didn't create a pull for it. (and I currently don't plan to merge this branch, as I could not fix the Issue with this)

Are you sure you saw it in this pull?

I'll have look at the points you mentioned, and update this pull. Ok?
But not today, I have to see when I have enough time.

**Comment by woheller69** [comment]
Regarding Logger you are right.
I downloaded your complete repo and then checked out, compiled, and tested the MobileWebpage branch.
But when I reviewed the code I marked all your commits and this also included the commit containing the Logger...

And Yes, just update this pull

PS: I also had an issue today where the REST API continued running and the camera service stopped. I had to reboot until it worked again. It seems the camera was not available.  I think these are hardware driver / OS issues and not related to the code in this app.

**Comment by andreasb242** [comment]
> * the http connection info is: http:///192.168.....  but should be http://.... so one "/" less, right? RestService.getLocalInetAddress(ctx) returns /192.168.....
Fixed (it's the toString method, therefore I just removed one slash from HTTP)
> 
> * when switching from JPG mode to a video mode, the image most recent image should be removed from the website
> 
fixed

> * "Refresh to get current image / No image to display" should only be displayed while in JPG mode
> 
fixed
> * When you click "Refresh" in video mode also the last image is loaded which should not be the case
> 
fixed
> * if the port is changed, http:// info is not updated, only when you click on it. Also after onResume ip info should be updated
> 
On port change the URL is updated.
> * For a release I would remove the Logger stuff. Or do you want to keep it? Then the log file should better be in the TimeLapseCam folder where also the images and videos are stored to have everything in one place
> 
not within this branch
> * Log.i(TAG, "Photo service destroyed"); in ForegroundService should better be "Recording service destroyed"
> 
not within this branch

> * In MainActivity there is a long uncommented block 	"// because of the crash it's not a"  which can probably be removed
not within this branch

**Pull request merged**
