### PR TITLE
Camera2 Implementation

### PR DESCRIPTION
**Pull request by andreasb242**
I fully implemented Camera 2 Image mode.
There are probably some bugs, it was really a lot to do. I marked it as beta. I would like to merge it, if there are no blocking issues, and I'll later fix bugs in small pull requests, if they are found.

There is a complete new Preview for the Camera 2 Interface, which supports the configuration of the Camera.
- Focus Configuration (hard to test, I need to build a special setup to make sure it's really 100% working)
- ISO and Exposure configuration: You need to configure both, or I need to do further investigation, how half manual needs to implemented correctly, if I just set ISO, I didn't get what I expected
- You can select the camera, on a Samsung with multi lens I could select the wide Angle, but the Macro was not list. On a Xiaomi I could not select the other Cameras, further investigation needed.
- White Balance can be configure
- Image scheduling is no independent of the last image result, so it not just crashes if the result was not called
- Errors are displayed
- There is a new OLED screen, which should prevent OLED burn in, but display some state (may be extended, doesen't display much yet)
- I fixed the preview to portrait, the most camera apps don't flip much, it's a lot of work to get it rotated perfectly, so I stopped the work there, because I think it's a low prio issue. If somebody like to deal with transformation matrix, feel free to do it :-) I spend to much time already to get the image scaled correctly in the portrait mode....

Video is not yet implemented, my target is to get picture mode reliable running first. As the whole camera configuration is already done, it's probably not that much work, the preview and the menus were a lot of work to do.

@woheller69 can you look at it in the near future?

### CODE REVIEW

**Comment by woheller69** [comment]
Sounds great. I will try it in the next days.
But we are not in a hurry of merging it. I am not planning any changes to the app right now, so we have time.
We can upload a beta apk in an issue so people can try it as beta and provide feedback.

**Comment by andreasb242** [comment]
>I am not planning any changes to the app right now, so we have time.
Good to know, thanks. It's really hard to merge such big pull requests...

I did some tests, and at least configure the focus to a field is working!

Autofocus:
TimeLapseCam116 resized

Focus configured:
TimeLapseCam117 resized

**Comment by andreasb242** [comment]
@woheller69 Can you create a new branch like "next-release", "beta", whatever.
We merge this branch, and you can create a beta build from it. You can control, which changes will be merged into the beta, and which not. And you decide, when you merge the branch back to master.

And I can do my development without caring to much about your releases.

I don't plan big changes, probably just bugfixes and small improvements, to get it reliable and comfortable running, as I like to use the app myself for Timelapse recording.

**Comment by woheller69** [comment]
First tests:
- the app crashes directly after first start (java.lang.RuntimeException: Unable to start service at.andreasrohner.spartantimelapserec.Camera1ForegroundService); second start works
- OLED status: text partially invisible (outside the screen range)
- Crash with new JPG mode:

2024-05-06 13:12:26.804 21143-21194 HttpThread              org.woheller69.TimeLapseCam          E  Camera Ready
2024-05-06 13:12:27.806 21143-21194 HttpThread              org.woheller69.TimeLapseCam          I  Take Image
2024-05-06 13:12:28.239 21143-21195 ImageReader_JNI         org.woheller69.TimeLapseCam          W  Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
2024-05-06 13:12:28.806 21143-21194 HttpThread              org.woheller69.TimeLapseCam          I  Take Image
2024-05-06 13:12:28.807 21143-21194 HttpThread              org.woheller69.TimeLapseCam          E  Still waiting for the last image! missed count: 0
2024-05-06 13:12:29.807 21143-21194 HttpThread              org.woheller69.TimeLapseCam          I  Take Image
2024-05-06 13:12:29.808 21143-21194 HttpThread              org.woheller69.TimeLapseCam          E  Still waiting for the last image! missed count: 1
2024-05-06 13:12:30.808 21143-21194 HttpThread              org.woheller69.TimeLapseCam          I  Take Image
2024-05-06 13:12:30.809 21143-21194 HttpThread              org.woheller69.TimeLapseCam          E  Still waiting for the last image! missed count: 2
2024-05-06 13:12:30.811 21143-21194 HttpThread              org.woheller69.TimeLapseCam          E  Could not create the last 3 images!
2024-05-06 13:12:30.887 21143-21194 HttpThread              org.woheller69.TimeLapseCam          E  Error: Could not create the last 3 images!
2024-05-06 13:12:35.710 21143-21143 HttpThread              org.woheller69.TimeLapseCam          I  Stop Service
2024-05-06 13:12:35.710 21143-21143 HttpThread              org.woheller69.TimeLapseCam          I  Rec mode: CAMERA2_TIME_LAPSE
2024-05-06 13:12:37.886 21143-21195 AndroidRuntime          org.woheller69.TimeLapseCam          E  FATAL EXCEPTION: Picture Thread
                                                                                                    Process: org.woheller69.TimeLapseCam, PID: 21143
                                                                                                    java.lang.IllegalStateException: Session has been closed; further changes are illegal.
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:903)
                                                                                                    	at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:180)
                                                                                                    	at at.andreasrohner.spartantimelapserec.camera2.TakePicture$2.onConfigured(TakePicture.java:109)
                                                                                                    	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$android-hardware-camera2-impl-CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
                                                                                                    	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda6.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by andreasb242** [comment]
>there is no powerSavingRecorder like for camera1, which is used when the interval is longer than a few seconds, right?
No, but this be easy integrated again if need. It's used if the Intervall is bigger than 10s.

**Comment by andreasb242** [comment]
>2024-05-06 19:29:24.696 14355-14425 ImageReader_JNI         org.woheller69.TimeLapseCam          W  Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers

This can be reproduced, if I set the timer to 10ms, which means 100 Images per Second.
On my Samsung it's not crashing, but I have to think about handling it better.

**Comment by woheller69** [comment]
I had 1 image per second and front camera

**Comment by TigFur** [comment]
I have no experience with any of this but i finally got to a pc and decided to give a try in building the apk to test it myself.
[timelapsecam2.txt](https://github.com/user-attachments/files/22311411/timelapsecam2.txt) (changed apk to txt)
I took the camera2 branch, i also tried a "beta" branch but since that one bugs when the timer is less than 5 seconds i think its an older version?

Anyway the camera2 solves many of the issues. ISO, lens, exposure and white balance are adjustable and function well. White balance only has some presets, adding manual would be great but its good enough.
But the focus.. not so much.

In both of these branches the issue was the same as with the main i tested. There are autofocus and semi manual focus options. 
Seemingly the semi manual would solve the refocus issue but it does not.
After the focus is set when the camera is re-engaged its lost again. Even just switching from the camera view, setting it up, returning to menu and going back to camera view shows this. You can go back and forth and the focus would be different each time even after the manual set. Same behavior is then in the process of taking pictures in background. The way i understand it the manual focus only chooses a smaller area for the auto focus finder so the underlying issue will be either in the autofocus or its resetting.
When the camera engages, the focus seems to default to something and ignore or shift the refocus or the manual focus setting. Maybe its some random aspect in where the focus starts or the values are incorrectly fetched or used.

Id still suggest adding a manual focus slider if possible, if the issue is in the auto focus, this might circumvent it.

**Pull request merged**
